// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetContentBlockIdsData, GetContentBlockIdsResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.nodeId
 * @param data.culture
 * @returns string OK
 * @throws ApiError
 */
export const getContentBlockIds = (data: GetContentBlockIdsData = {}): CancelablePromise<GetContentBlockIdsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/management/api/v1/AnchorEditor/GetContentBlockIds',
    query: {
        nodeId: data.nodeId,
        culture: data.culture
    }
}); };