// This file is auto-generated by @hey-api/openapi-ts

export type GetContentBlockIdsData = {
    culture?: string;
    nodeId?: string;
};

export type GetContentBlockIdsResponse = Array<(string)>;

export type $OpenApiTs = {
    '/umbraco/management/api/v1/AnchorEditor/GetContentBlockIds': {
        get: {
            req: GetContentBlockIdsData;
            res: {
                /**
                 * OK
                 */
                200: Array<(string)>;
            };
        };
    };
};